In [1]:
import polars as pl
import os
from sqlalchemy import create_engine
from os import listdir, environ
from openhexa.toolbox.dhis2.dataframe import get_organisation_units, get_data_elements
from openhexa.sdk import workspace, current_run
from openhexa.toolbox.dhis2 import DHIS2

ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/opt/conda/lib/python3.13/site-packages/traitlets/traitlets.py", line 632, in get
    value = obj._trait_values[self.name]
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '_control_lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py", line 565, in _log_error
    f.result()
    ~~~~~~~~^^
  File "/opt/conda/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 340, in dispatch_control
    async with self._control_lock:
               ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.13/site-packages/traitlets/traitlets.py", line 687, in __get__
    return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
                     ~~~~~~~~^^^^^^^^^^
  File "/opt/conda/lib/python3.13/site-packages/traitlets/traitlets.py", line 649, in get
    value = self._validate(obj, default)
  File "/opt/conda/lib/python3.13/site-packages/traitlets/traitlets.py", line 722, in _validate
    value = self.validate(obj, value)
  File "/opt/conda/lib/python3.13/site-packages/traitlets/traitlets.py", line 2311, in validate
    self.error(obj, value)
    ~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/conda/lib/python3.13/site-packages/traitlets/traitlets.py", line 831, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The '_control_lock' trait of an IPythonKernel instance expected a Lock, not the NoneType None.

In [2]:
os.getcwd()

'/home/jovyan/workspace/notebooks'

In [3]:
save_in_db = True

In [4]:
con = workspace.dhis2_connection("pbf-mali-blsq")
dhis = DHIS2(con)

## Lets get the ous

In [5]:
ous_dhis2 = get_organisation_units(dhis)

In [6]:
ous_dhis2.head()

shape: (5, 22)
┌────────────┬───────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id         ┆ name      ┆ level ┆ opening_da ┆ … ┆ level_7_na ┆ level_8_i ┆ level_8_n ┆ geometry  │
│ ---        ┆ ---       ┆ ---   ┆ te         ┆   ┆ me         ┆ d         ┆ ame       ┆ ---       │
│ str        ┆ str       ┆ i64   ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str       │
│            ┆           ┆       ┆ datetime[m ┆   ┆ str        ┆ str       ┆ str       ┆           │
│            ┆           ┆       ┆ s]         ┆   ┆            ┆           ┆           ┆           │
╞════════════╪═══════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ cKcuEmNzNF ┆ Mali      ┆ 1     ┆ 1960-09-22 ┆ … ┆ null       ┆ null      ┆ null      ┆ {"type":  │
│ 2          ┆           ┆       ┆ 00:00:00   ┆   ┆            ┆           ┆           ┆ "Polygon" │
│            ┆           ┆       ┆            ┆   ┆            ┆           ┆           ┆ , "coordi │
│            ┆           ┆       ┆            ┆   ┆            ┆           ┆           ┆ nat…      │
│ B3EA5FksXh ┆ Mali_del  ┆ 1     ┆ 1923-11-30 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 3          ┆           ┆       ┆ 00:00:00   ┆   ┆            ┆           ┆           ┆           │
│ K2bbWqZzyr ┆ Bamako    ┆ 2     ┆ 1960-09-22 ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ T          ┆           ┆       ┆ 00:00:00   ┆   ┆            ┆           ┆           ┆           │
│ b8cPdByQrS ┆ Gao       ┆ 2     ┆ 1960-09-22 ┆ … ┆ null       ┆ null      ┆ null      ┆ {"type":  │
│ G          ┆           ┆       ┆ 00:00:00   ┆   ┆            ┆           ┆           ┆ "Polygon" │
│            ┆           ┆       ┆            ┆   ┆            ┆           ┆           ┆ , "coordi │
│            ┆           ┆       ┆            ┆   ┆            ┆           ┆           ┆ nat…      │
│ GTkaSxaspw ┆ Koulikoro ┆ 2     ┆ 1960-09-22 ┆ … ┆ null       ┆ null      ┆ null      ┆ {"type":  │
│ x          ┆           ┆       ┆ 00:00:00   ┆   ┆            ┆           ┆           ┆ "Polygon" │
│            ┆           ┆       ┆            ┆   ┆            ┆           ┆           ┆ , "coordi │
│            ┆           ┆       ┆            ┆   ┆            ┆           ┆           ┆ nat…      │
└────────────┴───────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

## And the services

In [7]:
des = get_data_elements(dhis)

In [8]:
des = des.drop("value_type")

In [9]:
des.head()

shape: (5, 2)
┌─────────────┬────────────────────────┐
│ id          ┆ name                   │
│ ---         ┆ ---                    │
│ str         ┆ str                    │
╞═════════════╪════════════════════════╡
│ ZadItokqlHj ┆ A. Population a        │
│ l4h0CAPfWNY ┆ Autorité de gestion    │
│ wImika3f8ds ┆ BAQ Investissement     │
│ PVQmOpt9mOa ┆ Baq performance manuel │
│ Lhi3NhbG9Hz ┆ BAQ Recrutement        │
└─────────────┴────────────────────────┘

## Load the things

In [10]:
ous = pl.read_parquet(
    "/home/jovyan/workspace/pipelines/initialize_vbr/data/inconsistencies/ous_model_june.parquet"
)
services = pl.read_parquet(
    "/home/jovyan/workspace/pipelines/initialize_vbr/data/inconsistencies/services_model_june.parquet"
).filter(pl.col("quarter").is_in(["2025Q2","2025Q3","2025Q4","2026Q1"]))

In [105]:
quant_data = pl.read_csv(
    "/home/jovyan/workspace/pipelines/initialize_vbr/data/quantity_data/model_june_cleaned.csv"
)
quant_data_dirty = pl.read_csv(
    "/home/jovyan/workspace/pipelines/initialize_vbr/data/quantity_data/model_june_not_cleaned.csv"
)

In [45]:
ous_payment_with_data = quant_data.filter(
    (pl.col("quarter").is_in(["2025Q2", "2025Q3", "2025Q4", "2026Q1"]))
    & (pl.col("dec").is_not_null())
    & (pl.col("val").is_not_null())
    & (pl.col("payment_mode").is_not_null())
).select(["ou", "payment_mode"]).unique()

In [108]:
quant_data_dirty.filter((pl.col("payment_mode").str.contains("paiement_dispensaire")) & (pl.col("month").str.contains("2025Q3"))).sort(by="service")

shape: (0, 30)
┌─────┬───────┬─────────┬─────┬───┬────────────┬────────────────────┬────────────────────┬─────────┐
│ ou  ┆ month ┆ service ┆ dec ┆ … ┆ gain_verif ┆ subside_sans_verif ┆ subside_avec_verif ┆ quarter │
│ --- ┆ ---   ┆ ---     ┆ --- ┆   ┆ ---        ┆ ication            ┆ ication            ┆ ---     │
│ str ┆ str   ┆ str     ┆ f64 ┆   ┆ f64        ┆ ---                ┆ ---                ┆ str     │
│     ┆       ┆         ┆     ┆   ┆            ┆ f64                ┆ f64                ┆         │
╞═════╪═══════╪═════════╪═════╪═══╪════════════╪════════════════════╪════════════════════╪═════════╡
└─────┴───────┴─────────┴─────┴───┴────────────┴────────────────────┴────────────────────┴─────────┘

## Inconsistencies in the ous

In [11]:
ous.head()

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ payment_m ┆ Valide,   ┆ Valide,   ┆ Contracts ┆ … ┆ Hesabu:   ┆ Hesabu:   ┆ Dataset:  ┆ Dataset: │
│ ode       ┆ according ┆ according ┆ ---       ┆   ┆ In        ┆ In        ┆ In        ┆ In       │
│ ---       ┆ to Hesabu ┆ to        ┆ list[str] ┆   ┆ Valide,   ┆ Declare,  ┆ Valide,   ┆ Declare, │
│ str       ┆ ---       ┆ Dataset   ┆           ┆   ┆ not in    ┆ not in    ┆ not in    ┆ not in   │
│           ┆ list[str] ┆ ---       ┆           ┆   ┆ Decl…     ┆ Val…      ┆ Dec…      ┆ Va…      │
│           ┆           ┆ list[str] ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[null ┆ list[null ┆ list[str] ┆ list[str │
│           ┆           ┆           ┆           ┆   ┆ ]         ┆ ]         ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ paiement_ ┆ ["ZdmA07H ┆ ["ZdmA07H ┆ ["QzzGgSt ┆ … ┆ []        ┆ []        ┆ ["sVFqRLW ┆ ["U6N0Ny │
│ pma       ┆ 7tU8",    ┆ 7tU8",    ┆ 7xzD",    ┆   ┆           ┆           ┆ wOzp",    ┆ B4UFX",  │
│           ┆ "jsP1yc2j ┆ "jsP1yc2j ┆ "GWnlOrO7 ┆   ┆           ┆           ┆ "WRcK01zD ┆ "knCps0C │
│           ┆ M3m",…    ┆ M3m",…    ┆ 6RC",…    ┆   ┆           ┆           ┆ uy9",…    ┆ ta3j",…  │
│ paiement_ ┆ ["Mx7waSW ┆ ["Mx7waSW ┆ ["QzzGgSt ┆ … ┆ []        ┆ []        ┆ []        ┆ []       │
│ pca       ┆ hJ9Q",    ┆ hJ9Q",    ┆ 7xzD",    ┆   ┆           ┆           ┆           ┆          │
│           ┆ "pq9bZ5x4 ┆ "pq9bZ5x4 ┆ "GWnlOrO7 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 38C",…    ┆ 38C",…    ┆ 6RC",…    ┆   ┆           ┆           ┆           ┆          │
│ paiement_ ┆ ["CFwf7AW ┆ ["CFwf7AW ┆ ["QzzGgSt ┆ … ┆ []        ┆ []        ┆ ["Vav1PFA ┆ ["wdjVWy │
│ site      ┆ 8c08",    ┆ 8c08",    ┆ 7xzD",    ┆   ┆           ┆           ┆ TiSt",    ┆ TOvhz",  │
│           ┆ "Is61QHoG ┆ "Is61QHoG ┆ "GWnlOrO7 ┆   ┆           ┆           ┆ "D9gTr2Js ┆ "aN2R0yQ │
│           ┆ g2X",…    ┆ g2X",…    ┆ 6RC",…    ┆   ┆           ┆           ┆ vyS",…    ┆ yfni",…  │
│ paiement_ ┆ ["Aej6sua ┆ ["Aej6sua ┆ ["QzzGgSt ┆ … ┆ []        ┆ []        ┆ ["lDJEJHN ┆ ["YzVCQy │
│ prive     ┆ hktX",    ┆ hktX",    ┆ 7xzD",    ┆   ┆           ┆           ┆ Rg2E",    ┆ BgTzD",  │
│           ┆ "WdLrCzPh ┆ "WdLrCzPh ┆ "GWnlOrO7 ┆   ┆           ┆           ┆ "BVNP1OEI ┆ "rpSea3T │
│           ┆ 7RD",…    ┆ 7RD",…    ┆ 6RC",…    ┆   ┆           ┆           ┆ 6Pa",…    ┆ RrkG"]   │
│ paiement_ ┆ ["yWdYav6 ┆ ["Is61QHo ┆ ["QzzGgSt ┆ … ┆ []        ┆ []        ┆ ["nOmqIkT ┆ []       │
│ maternite ┆ Bujs",    ┆ Gg2X",    ┆ 7xzD",    ┆   ┆           ┆           ┆ 1EGS"]    ┆          │
│           ┆ "LoITEQJB ┆ "LoITEQJB ┆ "GWnlOrO7 ┆   ┆           ┆           ┆           ┆          │
│           ┆ wbV",…    ┆ wbV",…    ┆ 6RC",…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

What I want to do is create a table in SuperSet where I can visualize this information:
- A column that has the organisational unit
- A column that has the payment mode
- A column that has the source (hesabu / dataset / contracts)
- A column that has the declared and validated with a yes or a no.

The goal is that in this table, the client can filter very easily to see the incoherences...

In [12]:
relevant_ous = ous.select(
    [
        "payment_mode",
        "Valide, according to Hesabu",
        "Valide, according to Dataset",
        "Contracts",
        "Declare, according to Hesabu",
        "Declare, according to Dataset",
    ]
)

In [13]:
id_col = "payment_mode"
value_cols = [c for c in relevant_ous.columns if c != id_col]

long_df = (
    relevant_ous.unpivot(
        index=id_col, on=value_cols, variable_name="raw_column", value_name="org_units"
    )
    .filter(pl.col("org_units").is_not_null())
    .explode("org_units")
    .rename({"org_units": "org_unit"})
)

In [14]:
mapped_df = (
    long_df
    .with_columns(
        pl.when(pl.col("raw_column") == "Declare, according to Hesabu")
          .then(pl.lit(["declare_hesabu"]))
        .when(pl.col("raw_column") == "Valide, according to Hesabu")
          .then(pl.lit(["valide_hesabu"]))
        .when(pl.col("raw_column") == "Declare, according to Dataset")
          .then(pl.lit(["declare_dataset"]))
        .when(pl.col("raw_column") == "Valide, according to Dataset")
          .then(pl.lit(["valide_dataset"]))
        .when(pl.col("raw_column") == "Contracts")
          .then(pl.lit(["declare_contracts", "valide_contracts"]))  # duplicated
        .otherwise(pl.lit([]))
        .alias("indicator")
    ))

In [15]:
exploded_df = mapped_df.drop("raw_column").explode("indicator")
final_df = (
    exploded_df.with_columns(pl.lit(True).alias("present"))
    .pivot(
        index=["org_unit", "payment_mode"],
        on="indicator",
        values="present",
    )
    .fill_null(False)
)

## Merge the things and do some extra cleaning
For the level_1_name = "Mali_del", the things are never in the dataset -- this makes sense and should probably be raised to the client, who might want to update the contracts and the hesabu configs. (note that there are some cases in which the no-longer-used organisationalUnit is still in Hesabu, still in the contracts, or still in both.

I have also filtered to only include the organisationUnits that actually have data. There are still some of them that are not in hesabu, not in the contracts, or not in any of them. There is also difference between being assigned to the valide and to the declare (which I find very worrying).

In [64]:
merged = final_df.join(ous_dhis2, left_on="org_unit", right_on="id", how="left")

In [65]:
merged.filter(pl.col("level_1_name") == "Mali_del").select(
    [
        "valide_dataset",
        "declare_dataset",
        "valide_hesabu",
        "declare_hesabu",
        "valide_contracts",
        "declare_contracts",
        
        
    ]
).unique()

shape: (3, 6)
┌────────────────┬────────────────┬───────────────┬────────────────┬───────────────┬───────────────┐
│ valide_dataset ┆ declare_datase ┆ valide_hesabu ┆ declare_hesabu ┆ valide_contra ┆ declare_contr │
│ ---            ┆ t              ┆ ---           ┆ ---            ┆ cts           ┆ acts          │
│ bool           ┆ ---            ┆ bool          ┆ bool           ┆ ---           ┆ ---           │
│                ┆ bool           ┆               ┆                ┆ bool          ┆ bool          │
╞════════════════╪════════════════╪═══════════════╪════════════════╪═══════════════╪═══════════════╡
│ false          ┆ false          ┆ false         ┆ false          ┆ true          ┆ true          │
│ false          ┆ false          ┆ true          ┆ true           ┆ true          ┆ true          │
│ false          ┆ false          ┆ true          ┆ true           ┆ false         ┆ false         │
└────────────────┴────────────────┴───────────────┴────────────────┴───────────────┴───────────────┘

In [66]:
ous_really_cleaned = merged.filter(pl.col("level_1_name") != "Mali_del")

In [67]:
ous_really_cleaned = ous_really_cleaned.join(ous_payment_with_data, left_on = ["org_unit", "payment_mode"], right_on = ["ou", "payment_mode"], how="inner")

In [68]:
ous_really_cleaned.select(
    [
        "valide_dataset",
        "declare_dataset",
        "valide_hesabu",
        "declare_hesabu",
        "valide_contracts",
        "declare_contracts",
        
        
    ]
).unique()

shape: (6, 6)
┌────────────────┬────────────────┬───────────────┬────────────────┬───────────────┬───────────────┐
│ valide_dataset ┆ declare_datase ┆ valide_hesabu ┆ declare_hesabu ┆ valide_contra ┆ declare_contr │
│ ---            ┆ t              ┆ ---           ┆ ---            ┆ cts           ┆ acts          │
│ bool           ┆ ---            ┆ bool          ┆ bool           ┆ ---           ┆ ---           │
│                ┆ bool           ┆               ┆                ┆ bool          ┆ bool          │
╞════════════════╪════════════════╪═══════════════╪════════════════╪═══════════════╪═══════════════╡
│ true           ┆ true           ┆ false         ┆ false          ┆ false         ┆ false         │
│ true           ┆ true           ┆ true          ┆ true           ┆ false         ┆ false         │
│ false          ┆ true           ┆ false         ┆ false          ┆ true          ┆ true          │
│ true           ┆ true           ┆ true          ┆ true           ┆ true          ┆ true          │
│ true           ┆ true           ┆ false         ┆ false          ┆ true          ┆ true          │
│ true           ┆ false          ┆ false         ┆ false          ┆ true          ┆ true          │
└────────────────┴────────────────┴───────────────┴────────────────┴───────────────┴───────────────┘

In [52]:
ous_really_cleaned = merged_sel.filter(pl.col("level_1_name") != "Mali_del")

## Save into a database

In [54]:
ous_inconsistents = ous_really_cleaned.to_pandas()

In [55]:
if save_in_db:
    engine = create_engine(environ["WORKSPACE_DATABASE_URL"])
    database_name = "inconsistencies_ous"
    ous_inconsistents.to_sql(database_name, con = engine, if_exists="replace")

## Lets do some extra explorations

# Now, services

In [21]:
services.head()

shape: (5, 12)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ payment_mo ┆ quarter ┆ indicator ┆ Declare:  ┆ … ┆ Valide:   ┆ Tarif_def ┆ Tarif_def ┆ Tarif_def │
│ de         ┆ ---     ┆ s         ┆ Services  ┆   ┆ Percentag ┆ :         ┆ : List of ┆ : Percent │
│ ---        ┆ str     ┆ ---       ┆ not in    ┆   ┆ e of      ┆ Services  ┆ services  ┆ age of    │
│ str        ┆         ┆ list[str] ┆ Hesab…    ┆   ┆ nulls ro… ┆ not in    ┆ no…       ┆ nulls…    │
│            ┆         ┆           ┆ ---       ┆   ┆ ---       ┆ Hes…      ┆ ---       ┆ ---       │
│            ┆         ┆           ┆ str       ┆   ┆ str       ┆ ---       ┆ list[str] ┆ str       │
│            ┆         ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ paiement_p ┆ 2025Q2  ┆ ["declare ┆ 3 / 36    ┆ … ┆ 7.37      ┆ 4 / 37    ┆ ["xY9uofE ┆           │
│ ma         ┆         ┆ ",        ┆           ┆   ┆           ┆           ┆ Zq2r",    ┆           │
│            ┆         ┆ "valide", ┆           ┆   ┆           ┆           ┆ "hxkWry4H ┆           │
│            ┆         ┆ "tarif_d… ┆           ┆   ┆           ┆           ┆ oRC",…    ┆           │
│ paiement_p ┆ 2025Q3  ┆ ["declare ┆ 3 / 36    ┆ … ┆ 3.51      ┆ 9 / 42    ┆ ["b9OmkKr ┆           │
│ ma         ┆         ┆ ",        ┆           ┆   ┆           ┆           ┆ JevY",    ┆           │
│            ┆         ┆ "valide", ┆           ┆   ┆           ┆           ┆ "UtDknCwM ┆           │
│            ┆         ┆ "tarif_d… ┆           ┆   ┆           ┆           ┆ y4H",…    ┆           │
│ paiement_p ┆ 2025Q4  ┆ ["declare ┆ 4 / 37    ┆ … ┆ 1.96      ┆ 10 / 43   ┆ ["ssXW5Cz ┆           │
│ ma         ┆         ┆ ",        ┆           ┆   ┆           ┆           ┆ 38IB",    ┆           │
│            ┆         ┆ "valide", ┆           ┆   ┆           ┆           ┆ "hxkWry4H ┆           │
│            ┆         ┆ "tarif_d… ┆           ┆   ┆           ┆           ┆ oRC",…    ┆           │
│ paiement_p ┆ 2026Q1  ┆ ["declare ┆ 3 / 36    ┆ … ┆ 2.31      ┆ 10 / 43   ┆ ["ssXW5Cz ┆           │
│ ma         ┆         ┆ ",        ┆           ┆   ┆           ┆           ┆ 38IB",    ┆           │
│            ┆         ┆ "valide", ┆           ┆   ┆           ┆           ┆ "b9OmkKrJ ┆           │
│            ┆         ┆ "tarif_d… ┆           ┆   ┆           ┆           ┆ evY",…    ┆           │
│ paiement_p ┆ 2025Q2  ┆ ["declare ┆ 5 / 39    ┆ … ┆ 4.38      ┆ 3 / 37    ┆ ["eRWIQ3G ┆           │
│ ca         ┆         ┆ ",        ┆           ┆   ┆           ┆           ┆ Z8TY",    ┆           │
│            ┆         ┆ "valide", ┆           ┆   ┆           ┆           ┆ "VbHGAiOB ┆           │
│            ┆         ┆ "tarif_d… ┆           ┆   ┆           ┆           ┆ Mez",…    ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

With this, I want a table that has
- A column with the payment_mode
- A column with the quarter
- A column with tarif, declare and valide -- with a yes or no indicating if they are present

And then I also need, for the ones that have ["declare","valide","tarif_def"] I want to create a table that has
- A column with the payment_mode
- A column with the quarter
- A column with the service
- A column with the declare, valide and tarif, indicating if it is there or not

In [88]:
present_indicators = (
    services
    .with_columns(
        pl.col("indicators").list.contains("declare").alias("declare"),
        pl.col("indicators").list.contains("valide").alias("valide"),
        pl.col("indicators").list.contains("tarif_def").alias("tarif"),
    )
    .select(
        "payment_mode",
        "quarter",
        "declare",
        "valide",
        "tarif",
    )
)

In [89]:
present_indicators = present_indicators.with_columns(
    pl.concat_str(
        pl.col("declare").cast(pl.Int8).cast(pl.String),
        pl.col("valide").cast(pl.Int8).cast(pl.String),
        pl.col("tarif").cast(pl.Int8).cast(pl.String),
        separator="_"
    ).alias("fingerprint")
)

In [90]:
present_indicators_weird_unpivoted = (
    present_indicators
    .group_by("payment_mode")
    .agg(
        pl.col("fingerprint").n_unique().alias("n_distinct_combos"),
        pl.col("quarter").n_unique().alias("n_quarters"),
        pl.col("quarter").sort().alias("quarters_present"),
        pl.col("fingerprint").sort().alias("fingerprints"),
    )
    .filter(
        (pl.col("n_distinct_combos") > 1)  # indicators differ across quarters
        | (pl.col("n_quarters") < 4)  # or some quarters are missing
    )
    .sort("payment_mode")
)
weird_indicators = present_indicators_weird_unpivoted.select(pl.col("payment_mode")).unique().to_series().to_list()

In [96]:
present_indicators_weird = present_indicators.filter(pl.col("payment_mode").is_in(weird_indicators)).drop("fingerprint")

In [98]:
present_indicators_weird = present_indicators_weird.to_pandas()

In [99]:
if save_in_db:
    engine = create_engine(environ["WORKSPACE_DATABASE_URL"])
    database_name = "inconsistencies_indicators"
    present_indicators_weird.to_sql(database_name, con = engine, if_exists="replace")

## And the other one

In [25]:
services_present_1 = services.filter(
    pl.col("indicators") == ["declare", "valide", "tarif_def"]
).select(
    [
        "payment_mode",
        "quarter",
        "Declare: List of services not in Hesabu",
        "Tarif_def: List of services not in Hesabu",
        "Valide: List of services not in Hesabu"
    ]
)

In [26]:
services_present_1

shape: (43, 5)
┌─────────────────┬─────────┬───────────────────┬────────────────────┬──────────────────────────┐
│ payment_mode    ┆ quarter ┆ Declare: List of  ┆ Tarif_def: List of ┆ Valide: List of services │
│ ---             ┆ ---     ┆ services not …    ┆ services no…       ┆ not i…                   │
│ str             ┆ str     ┆ ---               ┆ ---                ┆ ---                      │
│                 ┆         ┆ list[str]         ┆ list[str]          ┆ list[str]                │
╞═════════════════╪═════════╪═══════════════════╪════════════════════╪══════════════════════════╡
│ paiement_pma    ┆ 2025Q2  ┆ ["r5y4iAaiGAu",   ┆ ["xY9uofEZq2r",    ┆ []                       │
│                 ┆         ┆ "WAVrIW5NEhX",…   ┆ "hxkWry4HoRC",…    ┆                          │
│ paiement_pma    ┆ 2025Q3  ┆ ["s5DOhQ8E7pr",   ┆ ["b9OmkKrJevY",    ┆ ["AdkRTRB1Wq4",          │
│                 ┆         ┆ "r5y4iAaiGAu",…   ┆ "UtDknCwMy4H",…    ┆ "r0p5VaG6ATf",…          │
│ paiement_pma    ┆ 2025Q4  ┆ ["WAVrIW5NEhX",   ┆ ["ssXW5Cz38IB",    ┆ ["AdkRTRB1Wq4",          │
│                 ┆         ┆ "s5DOhQ8E7pr",…   ┆ "hxkWry4HoRC",…    ┆ "r0p5VaG6ATf",…          │
│ paiement_pma    ┆ 2026Q1  ┆ ["WAVrIW5NEhX",   ┆ ["ssXW5Cz38IB",    ┆ ["AdkRTRB1Wq4",          │
│                 ┆         ┆ "s5DOhQ8E7pr",…   ┆ "b9OmkKrJevY",…    ┆ "r0p5VaG6ATf",…          │
│ paiement_pca    ┆ 2025Q2  ┆ ["SQb6WynojTw",   ┆ ["eRWIQ3GZ8TY",    ┆ []                       │
│                 ┆         ┆ "dYgVbkbxzWs",…   ┆ "VbHGAiOBMez",…    ┆                          │
│ …               ┆ …       ┆ …                 ┆ …                  ┆ …                        │
│ paiement_cabsf  ┆ 2026Q1  ┆ []                ┆ []                 ┆ []                       │
│ paiement_cabmed ┆ 2025Q2  ┆ []                ┆ []                 ┆ []                       │
│ paiement_cabmed ┆ 2025Q3  ┆ []                ┆ []                 ┆ []                       │
│ paiement_cabmed ┆ 2025Q4  ┆ []                ┆ []                 ┆ []                       │
│ paiement_cabmed ┆ 2026Q1  ┆ []                ┆ []                 ┆ []                       │
└─────────────────┴─────────┴───────────────────┴────────────────────┴──────────────────────────┘

In [27]:
services_present_2 = (
    services_present_1
    .with_columns(
        pl.concat_list(
            pl.col("Declare: List of services not in Hesabu"),
            pl.col("Valide: List of services not in Hesabu"),
            pl.col("Tarif_def: List of services not in Hesabu"),
        )
        .list.unique()
        .alias("service")
    )
    .explode("service")
)
services_present_2 = services_present_2.filter(pl.col("service").is_not_null())

In [28]:
services_present_3 = (
    services_present_2
    .with_columns(
        pl.col("Declare: List of services not in Hesabu")
        .list.contains(pl.col("service"))
        .alias("declare"),

        pl.col("Valide: List of services not in Hesabu")
        .list.contains(pl.col("service"))
        .alias("valide"),

        pl.col("Tarif_def: List of services not in Hesabu")
        .list.contains(pl.col("service"))
        .alias("tarif"),
    )
    .select(
        "payment_mode",
        "quarter",
        "service",
        "declare",
        "valide",
        "tarif",
    )
)

In [29]:
services_present_4 = services_present_3.join(des, left_on="service", right_on="id")

In [30]:
services_present_5 = services_present_4.with_columns(
    pl.col("name")
    .str.replace("- déclaré ", "")
    .str.replace("- validé ", "")
    .str.replace("- tarif déf ", "")
    .str.replace("- tarif ", "")
    .str.replace("- tarif déf. ", "")
    .str.replace("- tarif_p ", "")
).drop("service")

In [31]:
services_present_6 = (
    services_present_5
    .group_by(["payment_mode", "quarter", "name"])
    .agg([
        pl.col("declare").any().alias("declare"),
        pl.col("valide").any().alias("valide"),
        pl.col("tarif").any().alias("tarif"),
    ])
)
services_present_6 = services_present_6.to_pandas()

In [32]:
if save_in_db:
    engine = create_engine(environ["WORKSPACE_DATABASE_URL"])
    database_name = "inconsistencies_services"
    services_present_6.to_sql(database_name, con = engine, if_exists="replace")